<a href="https://colab.research.google.com/github/Sakhiur2022/Signal/blob/main/notebooks/04_modeling/train_deision_tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import libraries

In [21]:
! pip install lazypredict

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.0/71.0 kB 2.1 MB/s eta 0:00:00


## Import dataset

In [1]:
! wget https://huggingface.co/datasets/Sakhiur/signal/resolve/main/final_dataset_preprocessed.csv

--2026-08-15 18:13:49--  https://huggingface.co/datasets/Sakhiur/signal/resolve/main/final_dataset_preprocessed.csv
Resolving huggingface.co (huggingface.co)... 143.204.181.47, 143.204.181.121, 143.204.181.85, ...
Connecting to huggingface.co (huggingface.co)|143.204.181.47|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://us.gcp.cdn.hf.co/xet-bridge-us/6a7c7183f2c81824bdfb6fa9/fe675c7c7a2b309373beb28e52da85ce564bdaabe871e6c19ad532f6073add3d?response-content-type=text%2Fcsv&X-Xet-Cas-Uid=public&user_id=public&response-content-disposition=inline%3B+filename*%3DUTF-8%27%27final_dataset_preprocessed.csv%3B+filename%3D%22final_dataset_preprocessed.csv%22%3B&Expires=1786821229&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly91cy5nY3AuY2RuLmhmLmNvL3hldC1icmlkZ2UtdXMvNmE3YzcxODNmMmM4MTgyNGJkZmI2ZmE5L2ZlNjc1YzdjN2EyYjMwOTM3M2JlYjI4ZTUyZGE4NWNlNTY0YmRhYWJlODcxZTZjMTlhZDUzMmY2MDczYWRkM2RcXD9yZXNwb25zZS1jb250ZW50LXR5cGU9KiZYLVhldC1DYXMtVWlkPXB1YmxpYyZ1c2V

## Import Libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Load dataset

In [3]:
dataset = pd.read_csv('final_dataset_preprocessed.csv')
dataset.head()

,age,education_years,weekly_workhours,digital_index,social_participation_index,gender_male,disabled,social_participant,agri_worker,disability_severity_ord,...,disability_hand_finger,no_disability,digital_status,income_class,region_Bali_Nusa,region_Eastern,region_Java,region_Kalimantan,region_Sulawesi,region_Sumatra
0,78.0,6.0,0.0,0.0,0.333333,1,0,1,0,0,...,0,1,0,No_income,0,0,0,0,0,1
1,65.0,6.0,0.0,0.0,0.333333,0,0,1,0,0,...,0,1,0,No_income,0,0,0,0,0,1
2,82.0,6.0,0.0,0.0,0.000000,1,0,0,0,0,...,0,1,0,No_income,0,0,0,0,0,1
3,65.0,6.0,0.0,0.0,0.000000,0,0,0,0,0,...,0,1,0,No_income,0,0,0,0,0,1
4,31.0,12.0,35.0,1.0,0.333333,1,0,1,0,0,...,0,1,2,Low,0,0,0,0,0,1


In [4]:
X = dataset.drop('income_class', axis=1)
y = dataset['income_class']

In [5]:
X

,age,education_years,weekly_workhours,digital_index,social_participation_index,gender_male,disabled,social_participant,agri_worker,disability_severity_ord,...,disability_communication,disability_hand_finger,no_disability,digital_status,region_Bali_Nusa,region_Eastern,region_Java,region_Kalimantan,region_Sulawesi,region_Sumatra
0,78.0,6.0,0.0,0.0,0.333333,1,0,1,0,0,...,0,0,1,0,0,0,0,0,0,1
1,65.0,6.0,0.0,0.0,0.333333,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,1
2,82.0,6.0,0.0,0.0,0.000000,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
3,65.0,6.0,0.0,0.0,0.000000,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
4,31.0,12.0,35.0,1.0,0.333333,1,0,1,0,0,...,0,0,1,2,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751617,25.0,1.0,36.0,0.0,0.333333,0,0,1,0,0,...,0,0,1,0,0,1,0,0,0,0
751618,33.0,1.0,36.0,0.0,0.333333,1,0,1,0,0,...,0,0,1,0,0,1,0,0,0,0
751619,25.0,1.0,36.0,0.0,0.333333,0,0,1,0,0,...,0,0,1,0,0,1,0,0,0,0
751620,36.0,1.0,36.0,0.0,0.333333,1,0,1,0,0,...,0,0,1,0,0,1,0,0,0,0


In [6]:
y

,income_class
0,No_income
1,No_income
2,No_income
3,No_income
4,Low
...,...
751617,No_income
751618,Medium
751619,No_income
751620,Medium


## Splitting the dataset into the Training set and Test set

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 42)

In [11]:
print(X_train)

         age  education_years  weekly_workhours  digital_index  \
198372  15.0              9.0               0.0            0.0   
560962  46.0              6.0              48.0            0.0   
161858  55.0              6.0              48.0            0.0   
123453  46.0              9.0              56.0            0.0   
84898   59.0             12.0              36.0            0.0   
...      ...              ...               ...            ...   
259178  30.0              6.0              63.0            2.0   
365838  43.0              6.0              56.0            1.0   
131932  28.0             12.0               0.0            0.0   
671155  34.0             12.0              56.0            1.0   
121958  20.0             12.0              70.0            0.0   

        social_participation_index  gender_male  disabled  social_participant  \
198372                    0.333333            0         0                   1   
560962                    0.333333           

In [12]:
print(y_train)

198372    No_income
560962       Medium
161858       Medium
123453       Medium
84898           Low
            ...    
259178       Medium
365838       Medium
131932    No_income
671155       Medium
121958       Medium
Name: income_class, Length: 601297, dtype: object


## Feature Scaling

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
print(X_train)

[[-1.56327321  0.04303375 -1.12152614 ... -0.3392775  -0.41857732
   1.54701239]
 [ 0.32026504 -0.64070429  0.97569275 ...  2.94743979 -0.41857732
  -0.64640723]
 [ 0.86709873 -0.64070429  0.97569275 ... -0.3392775  -0.41857732
   1.54701239]
 ...
 [-0.77340233  0.7267718  -1.12152614 ... -0.3392775  -0.41857732
   1.54701239]
 [-0.40884654  0.7267718   1.32522923 ... -0.3392775   2.38904485
  -0.64640723]
 [-1.25947671  0.7267718   1.93691808 ... -0.3392775  -0.41857732
   1.54701239]]


In [10]:
print(y_train)

198372    No_income
560962       Medium
161858       Medium
123453       Medium
84898           Low
            ...    
259178       Medium
365838       Medium
131932    No_income
671155       Medium
121958       Medium
Name: income_class, Length: 601297, dtype: object


## Training the Decision Tree Classification model on the Training set

In [11]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 42)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=42)

## Predicting the Test set results

In [12]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.values.reshape(len(y_test),1)),1))

[['No_income' 'No_income']
 ['Low' 'High']
 ['High' 'High']
 ...
 ['No_income' 'No_income']
 ['No_income' 'Medium']
 ['No_income' 'No_income']]


## Making the Confusion Matrix

In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[15246  4412  7291   948]
 [ 5078 12048  6994  4336]
 [ 9286  7599  9505  2011]
 [ 1316  5612  2319 56324]]


0.6194777981041077

## Classification summary

In [14]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

        High       0.49      0.55      0.52     27897
         Low       0.41      0.42      0.41     28456
      Medium       0.36      0.33      0.35     28401
   No_income       0.89      0.86      0.87     65571

    accuracy                           0.62    150325
   macro avg       0.54      0.54      0.54    150325
weighted avg       0.62      0.62      0.62    150325

